{
    'name': 'Hospital Management',
    'version': '1.0.0',
    'sequence': -100,
    'category':'',
    'summary':'',
    'depends': ['mail','product','report_xlsx'],
    'data':[
        'security/ir.model.access.csv',
        'data/patient_tag_data.xml',
        'data/patient.tag.csv',
        'wizard/cancel_appointement_view.xml',
        'views/menu.xml',
        'views/patient_view.xml',
        'views/female_patient_view.xml',
        'views/appointment_view.xml',
        'views/patient_tag_view.xml',
        'data/sequence.xml',
        'report/patient_card_template.xml',
        'report/report.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application':True,
    'assets':{}
}